apiVersion: v1
kind: Service
metadata:
  name: {{ template "tradefinance.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 4900
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "tradefinance.selectorLabels" . | nindent 4 }}
